<a href="https://colab.research.google.com/github/Surekha8Rajbhar/awesome-google-colab/blob/master/spamEmailExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#

**Description** 

This program detect if an email is spam (1) or not (0).

In [11]:
# import libraries

import numpy as np
import pandas as pd 
import nltk
from nltk.corpus import stopwords
import string 

In [17]:
# Load the data

from google.colab import files
uploaded= files.upload()

Saving emailss.csv to emailss.csv


In [20]:
# Read the CSV file

df= pd.read_csv('emailss.csv')

In [21]:
#print the first file rows of Data

df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [22]:
#Print the shape (get the number of rows and columns)

df.shape

(5728, 2)

In [23]:
#Get the columns names

df.columns

Index(['text', 'spam'], dtype='object')

In [24]:
#Check for dublicates

df.drop_duplicates(inplace=True)

In [25]:
#Show the new shape (number of rows and columns)

df.shape

(5695, 2)

In [26]:
#show the number of missing (NAN , NaN , na) data for each column

df.isnull().sum()

text    0
spam    0
dtype: int64

In [27]:
# Dwonload the stopwords package

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [32]:
def process_text(text):

#1. remove the punctuation 
#2. remove the stopewords
#3. return the list of clean text words

   nopunc= [char for char in text if char not in string.punctuation]
   nopunc=''.join(nopunc)

   clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

   return clean_words


In [33]:
#show the tokenization (a list of tokens also called lemans)

df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [40]:
#Example

message4= 'hello world hello hello world play'

message5= 'test test test test one hello'

print(message4)
print()

#convert the text to a matrix of token counts 
from sklearn.feature_extraction.text import CountVectorizer
bow4 =CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]])
print(bow4)
print()
print(bow4.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


In [41]:
# convert a collection of text to matrix of tokens

from sklearn.feature_extraction.text import CountVectorizer
message_blow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])



In [42]:
#split the data into 80% traning and 20% testing 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(message_blow, df['spam'], test_size=0.20, random_state=0)


In [43]:
#get the shape of the data

message_blow.shape

(5695, 37229)

In [44]:
#create and train the naive classifier

from sklearn.naive_bayes import MultinomialNB
classifier= MultinomialNB().fit(X_train, y_train)

In [48]:
#print the predictions

print(classifier.predict(X_train))

#print the actial values

print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [51]:
#Evaluate the model on the train data set

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion matrix:\n', confusion_matrix(y_train,pred))
print()
print ('Accuracy:', accuracy_score(y_train,pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion matrix:
 [[3445   12]
 [   1 1098]]

Accuracy: 0.9971466198419666


In [53]:
#print the predictions

print(classifier.predict(X_test))

#print the actial values

print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [54]:
#Evaluate the model on the train data set

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion matrix:\n', confusion_matrix(y_test,pred))
print()
print ('Accuracy:', accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion matrix:
 [[862   8]
 [  1 268]]

Accuracy: 0.9920983318700615
